export const products = [
  {
    id: 1,
    src: 'https://shopivate.pk/wp-content/uploads/2023/08/1000236536.jpg',
    name: 'Head Phone',
    price: 35,
    category: 'Electronics',
    description: 'best headphone with ultra battery duration',
  },
  {
    id: 2,
    src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTr7Hub0YN94UCKfl9iAB49vaRO0ieA-Cjx0KxLKVtjZnMqk51a2I4618Tnr-KnzbGJ00s&usqp=CAU',
    name: 'Keyboard',
    price: 45,
    category: 'Electronics',
    description: 'best Keyboard with ultra battery duration',
  },
  {
    id: 3,
    src: 'https://images.priceoye.pk/yolo-pulse-bluetooth-speaker-pakistan-priceoye-bh4h7.jpg',
    name: 'Bluetooth Speaker',
    price: 15,
    category: 'Electronics',
    description: 'best Speaker with ultra battery duration',
  },
  {
    id: 4,
    src: 'https://www.popsci.com/uploads/2021/03/24/Backlit_Compueter_Laptop.jpg?auto=webp',
    name: 'Led Tv',
    price: 25,
    category: 'Electronics',
    description: 'best Led Tv with ultra battery duration',
  },
  {
    id: 5,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 6,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 7,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },

  {
    id: 8,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 9,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 10,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 11,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 12,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 13,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 14,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 15,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 16,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 17,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 18,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 19,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },

  {
    id: 20,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
  {
    id: 21,
    src: 'https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg',
    name: 'Mouse',
    price: 30,
    category: 'Electronics',
    description: 'best Mouse with ultra battery duration',
  },
];
